### ISSUE TITLE
What is the meaning of the result?

### ISSUE THREAD

**Issue by jfoclpf** [LukaszKrawczyk/density-clustering#14]
Sorry the dumb question, but what is the meaning of the result? Initially I though it was some buggy doc, but just installed and confirmed

```js
var dataset = [
    [1,1],[0,1],[1,0],
    [10,10],[10,13],[13,13],
    [54,54],[55,55],[89,89],[57,55]
];
 
var clustering = require('density-clustering');
var dbscan = new clustering.DBSCAN();
// parameters: 5 - neighborhood radius, 2 - number of points in neighborhood to form a cluster
var clusters = dbscan.run(dataset, 5, 2);
console.log(clusters, dbscan.noise);
 
/*
RESULT:
[
    [0,1,2],
    [3,4,5],
    [6,7,9],
    [8]
]
 
NOISE: [ 8 ]
*/
```

Why 3 different clusters of points in 2D have as result a 3x3 matrix?

**Comment by jfoclpf** [comment]
WTF, it's the indexes of the array :)

**Comment by wesbos** [comment]
lol thank you. New to this stuff and I had no idea how to figure out which vectors were included in the arrays. I thought the result was a vector in itself. I slapped my head with your comment about it being the index
