### ISSUE TITLE
OPTICS: Core Distance Calculation

### ISSUE THREAD

**Issue by uarga** [LukaszKrawczyk/density-clustering#4]
Hey,

I believe that the core distance calculation is wrong.

Per definition, the core-distance of an object o is the smallest distance for o to be a core object.

Your function distanceToCore(pointId, neighbors):

```
minDistance = undefined;
if (neighbors.length >= this.minPts) {
    var minDistance = this.epsilon;
    neighbors.forEach(function(pointId2) {
        var dist = self.distance(self.dataset[pointId], self.dataset[pointId2]);
        if (dist < minDistance) minDistance = dist;
    });
}
return minDistance;
```

As far as I understand, you set the coreDistance to the distance to the nearest neighbor. That's wrong in genereal and would only be correct if there were a total of minPts many points as near as the nearest neighbor.

Here's a suggestion for distanceToCore:

```
OPTICS.prototype._distanceToCore = function(pointId) {

    var coreDistCand;
    for(coreDistCand = 0, l = this.epsilon; coreDistCand < l; coreDistCand++) {
      var neighbors = [];
      for (var id = 0, k = this.dataset.length; id < k; id++) {
        if (this.distance(this.dataset[pointId], this.dataset[id]) <= coreDistCand) {
          neighbors.push(id);
        }
      }
      if(neighbors.length >= this.minPts) {
        return coreDistCand;
      }
    }
    return -1;
}
```

**Comment by LukaszKrawczyk** [comment]
I've just released new version (1.2.0). From now core points are included in region queries, both in DBSCAN and OPTICS.
